// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVzWKomdCzIY6TlJVP7d2gRldcf4PjYqo',
    appId: '1:612574688210:web:dda2530db4bcdc0c2c0e0b',
    messagingSenderId: '612574688210',
    projectId: 'track-the-bus-434ee',
    authDomain: 'track-the-bus-434ee.firebaseapp.com',
    storageBucket: 'track-the-bus-434ee.firebasestorage.app',
    measurementId: 'G-JRTXJT91PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhdlyt4AK6q3kJzHeFbUVMkPGFk8NaQ8g',
    appId: '1:612574688210:android:342308b3e6598a252c0e0b',
    messagingSenderId: '612574688210',
    projectId: 'track-the-bus-434ee',
    storageBucket: 'track-the-bus-434ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVXbDuiIxNTQQ9NcsQadhrzLS4K8hMS6E',
    appId: '1:612574688210:ios:58a6fc4794d8b70a2c0e0b',
    messagingSenderId: '612574688210',
    projectId: 'track-the-bus-434ee',
    storageBucket: 'track-the-bus-434ee.firebasestorage.app',
    iosBundleId: 'com.example.trackTheBus',
  );
}
